<template>
  <svg
    width="16"
    height="17"
    viewBox="0 0 16 17"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect
      x="2.5"
      y="5"
      width="11"
      height="7"
      stroke="black"
      stroke-width="1.5"
    />
    <rect
      x="4.5"
      y="2.5"
      width="7"
      height="2.5"
      stroke="black"
      stroke-width="1.5"
    />
    <rect
      x="4.5"
      y="12"
      width="7"
      height="2.5"
      stroke="black"
      stroke-width="1.5"
    />
    <rect x="4.5" y="7.5" width="2" height="2" fill="black" />
  </svg>
</template>
